### ISSUE TITLE
dasm OS X release only runs on recent OS releases

### ISSUE THREAD

**Issue by msaarna** [dasm-assembler/dasm#104]
Ideally we'd cross-compile with OS X 10.5 (Leopard) libraries. Since OS X binaries are only forward compatible, this would serve more users.

Is there a technical reason we can't do this?

**Comment by dionoid** [comment]
Hi Mike, do you have an older version of OS X to test out this snapshot build:
https://github.com/dasm-assembler/dasm/suites/1410332815/artifacts/23536985

I've added `-mmacosx-version-min=10.5` to the CFLAGS when compiling for OS X, which I hope will support older OS X releases, while still using the latest MacOS SDK installed on the Github runner machines.

**Comment by msaarna** [comment]
Brilliant! I tested it out in my 10.7 OS X, and it runs just fine.

**Comment by dionoid** [comment]
fix merged to master. closing this issue
