### ISSUE TITLE
Doesn't load INCLUDE'ed libraries

### ISSUE THREAD

**Issue by Tux9001** [dasm-assembler/dasm#108]
Whenever I try to compile a program that involves built-in libraries, it doesn't work. Specifically, when I try to do the following, it complains that it can't open `vcs.h` and `macro.h`

```
	processor 6502
	include "vcs.h"
	include "macro.h"
```

**Comment by andrew-davie** [comment]
It's looking for those files in the base directory (the one in which your source file is located).
Are they there?

**Comment by Tux9001** [comment]
> 
> 
> It's looking for those files in the base directory (the one in which your source file is located).
> Are they there?

No, but other sources say it should work fine even if they aren't.

**Comment by andrew-davie** [comment]
dasm doesn't search your computer to find these files.
They have to be in a location/path that is known to the assembler.

**Comment by Tux9001** [comment]
Strange, everyone else says it works even if it isn't in the same directory. Thank you anyway.
