### ISSUE TITLE
Assembled output padded with 00 bytes

### ISSUE THREAD

**Issue by cpt-rexx** [dasm-assembler/dasm#126]
Greetings, 
Any code I assemble is padded at the beginning with two $00 bytes.
For example, this code:

```
        .processor      6502 
 
        .org    $0 
        cld             ; clear decimal flag

```

results in a binary file that contains:

`0000: 00 00 D8`

where I expected only:

`0000: D8`

What am I doing wrong?

**Comment by thrust26** [comment]
What's the -f flag you are using? -f3?

**Comment by cpt-rexx** [comment]
Hey Thomas,

Thanx for the quick reply.
I wasn’t using any -f flag.
Re-reading the docs I see:

1 default. The output file contains a two byte origin in little-endian order, then data until the end of the file.

Adding ‘-f3’ gives the output I want.

I knew I was doing something silly =:-o

Cheers,
Jason
