### ISSUE TITLE
Apple ARM Support 

### ISSUE THREAD

**Issue by PolarTechEd** [dasm-assembler/dasm#139]
Any chance we can get Apple ARM support?  I prefer not to have to deal with x86 emulation.

**Comment by andrew-davie** [comment]
> Any chance we can get Apple ARM support? I prefer not to have to deal with x86 emulation.

I'm not sure what you are asking for here?  You want dasm to run on M1/M2 MacOS? If so, the released binaries will run just fine without you needing to do anything, AFAIK.  Are you asking for ARM-native builds/distribution?

**Comment by PolarTechEd** [comment]
Yes, ARM-native builds/distributions.

Lawerence Schweitz,
Owner,
Northstar Consulting,
Phone: (775) 375-7583
E-Mail: ***@***.***
Web: https://northstarconsulting.tech
Twitter: @PolarTechEd

**Comment by andrew-davie** [comment]
OK, we should probably add these.  Meanwhile, though, building dasm locally is usually reasonably straightforward. Perhaps this is an option for you. I expect, though, there will be no noticeable difference between rosetta running the x86 version and arm native version, at least in terms of speed.
