### ISSUE TITLE
vcs.h redistribution

### ISSUE THREAD

**Issue by boeckmann** [dasm-assembler/dasm#140]
Hello, is it ok if I ship the vcs.h definition file with my own assembler? My assembler is licensed under BSD-3, and I would like to ask if I may put my adapted vcs.h version also under BSD-3.

**Comment by boeckmann** [comment]
As the original author and copyright owner you should be free to put the file under any license you want. What is needed is the permission of EVERY person who contributed to the file, or throw these parts out.

There are comments in the file I am interested in. Otherwise I could create the file from scratch. :-)

**Comment by andrew-davie** [comment]
Feel free to contact me privately ***@***.*** ***@***.***> to discuss, or via AtariAge PM
