### ISSUE TITLE
MacOS catalina - only 64-bit apps

### ISSUE THREAD

**Issue by andrew-davie** [dasm-assembler/dasm#16]
We need to add a precompiled 64-bit dasm download for MacOS, as the new catalina variant of the OS no longer runs 32 bit apps.

**Comment by dionoid** [comment]
Hmm, Apple is serious about this. I'll add 64-bit dasm downloads for the currently released version.

**Comment by dionoid** [comment]
Hi @andrew-davie, could you verify that this 64-bits build of dasm 2.20.11 works on your MacOS machine?

[dasm_2.20.11_macOS_64bits.zip](https://github.com/dasm-assembler/dasm/files/3721685/dasm_2.20.11_macOS_64bits.zip)

**Comment by andrew-davie** [comment]
Yep. Confirmed working OK on MacOS/Catalina.

**Comment by dionoid** [comment]
I updated the build script to include the 64-bit builds, and also added 64-bit release packages for the current 2.20.11 release. Also added links to these builds on the [dasm homepage](https://dasm-assembler.github.io/).
