### ISSUE TITLE
Makefile portability fixes

### ISSUE THREAD

**Issue by icepic** [dasm-assembler/dasm#19]
on OpenBSD, gmake is needed to run the Makefiles, but the rules refer to "make" which uses the native make instead, and doesn't work.

diff --git a/Makefile b/Makefile
index a8bd768..9bab1b1 100644
--- a/Makefile
+++ b/Makefile
@@ -38,13 +38,13 @@ install: build
 # just run all the tests
 test: build
        echo "Running tests..."
-       (cd test; make; cd ..)
+       (cd test; $(MAKE); cd ..)
        echo "Tests were run, but testing is not fully automated yet."
        echo "In other words, don't rely on what you saw too much."
 
 # just build everything and copy binaries to trunk/bin/
 build:
-       (cd src; make; cd ..)
+       (cd src; $(MAKE); cd ..)
        mkdir -p bin
        cp src/dasm bin/dasm
        cp src/ftohex bin/ftohex
@@ -115,6 +115,6 @@ beta:
 # regular build from this Makefile; don't delete the
 # "real" distribution archives
 clean:
-       (cd src; make clean; cd ..)
-       (cd test; make clean; cd ..)
+       (cd src; $(MAKE) clean; cd ..)
+       (cd test; $(MAKE) clean; cd ..)
        -rm -rf dasm-beta-*.tar.gz bin/
diff --git a/test/Makefile b/test/Makefile
index a36eb2c..1a3f585 100644
--- a/test/Makefile
+++ b/test/Makefile
@@ -5,7 +5,7 @@ DASM=../bin/dasm
 FTOHEX=../bin/ftohex
 
 test:
-       (cd atari2600; make test; cd ..)
+       (cd atari2600; $(MAKE) test; cd ..)
        ./run_tests.sh
 
 %.bin: %.asm
@@ -15,5 +15,5 @@ test:
        $(FTOHEX) 1 $< $@
 
 clean:
-       (cd atari2600; make clean; cd ..)
+       (cd atari2600; $(MAKE) clean; cd ..)
        rm -rf *.bin *.hex *.list.txt

**Comment by icepic** [comment]
hmm, markup made it look really weird.
"replace hardcoded name 'make' with $(MAKE) in two Makefiles" is the short version of it.

**Comment by msaarna** [comment]
Updated in the 2.20.13-SNAPSHOT master. Thanks!
