### ISSUE TITLE
DASM failing under Windows with Linux linefeeds

### ISSUE THREAD

**Issue by thrust26** [dasm-assembler/dasm#2]
When you try to assemble files under Windows which contain Linux line feeds, DASM frequently fails. Especially the REPEAT pseudo-op seems to be affected.

**Comment by dionoid** [comment]
This should be fixed in the 2.20.12 branch (fix done by @msaarna).
Let me add a test that verifies the fix.

**Comment by dionoid** [comment]
Solved in version 2.20.12
