### ISSUE TITLE
Historic versions available

### ISSUE THREAD

**Issue by Rhialto** [dasm-assembler/dasm#20]
Hi! Nice to see some new development on an old project of mine! I just recently heard about it so I had a look. 

It seems you lost the project history though. I just happen to have converted the svn history from sourceforge to git at https://gitlab.com/Rhialto/dasm-dillon . Since the original svn structure is a bit weird (and definitely nonstandard), the result reflects that. Would you be interested in replaying your changes on top of the history? Maybe we could re-arrange things a bit first, so that it makes more sense for the future.

**Comment by dionoid** [comment]
Hi Olaf, thanks for checking out one of your old projects. 
dasm is still very widely used in the Atari 2600/7800 homebrew developer scene, so thanks for all the work that you've done on dasm in the past!

This GitHub repo was created to have an official **single point** where the latest version of dasm is maintained and distributed. So in case you want to make changes/fixes to dasm, please do it based on this GitHub repo, and not on the project you've create on GitLab.

About your question: 
I've used the two full-source releases of dasm (2.20.11 and 2.20.12) from SourceForge as base of this GitHub repo. That also means that SourceForge commits after the 2.20.12 release (which was the commit named "RevEng 2014/02/02 update") are not in this GitHub repo, as they were never tested by the community that uses dasm.
I think the risk of messing up this GitHub repo is too high, when replaying older commits from another repo. Anyone who is interested could still go to SourceForge to see the changes done by Peter Froehlich from 2008 - 2015. Note that changes before 2008 (from Andrew or you) are not in that SourceForge repo, so it's not a full commit-history anyway.

Hope this answers your question.

Cheers,
Dion

**Comment by Rhialto** [comment]
A single definitive and authoritative location for DASM is definitely be a laudable goal, with which I fully agree.

I can also understand that you don't want to mix in, unseen, previsously unreleased code. The solution there is simple: find the point in the history that corresponds to your starting point, and replay your improvements from there. The original svn trunk can than be a side-branch (and you can determine at your leisure what you want to integrate from it). I'm sure replaying the changes won't be as simple as a single `git rebase` command, but it probably won't be very hard either. Probably it is the easiest to create a small script that creates a new repo from the various parts, and you can tweak the script and rerun it until it is perfect. No need to overwrite any repositories before that!

To send people to Sourceforge if they want to know older history does not seem like a good idea to me. It is contrary to the idea of one authoritative source location. Things that don't stay together get lost. In the case of Sourceforge, that risk is even bigger, since Sourceforge is declining in popularity (for some unfortunately valid reasons) for years now, and personally I expect it to disappear at any time. Those reasons are probably also why your project is not on Sourceforge but here.

And there is history from before 2008 in the svn repo (and its clone): it is in the "archeology" directory. In svn it is not really visible unless you know about it and explicitly check it out (that is why I call the repo layout a bit weird), but in the git conversion it is clearly there. It has versions that were still available around the net, going back to a 2.12 from Matt with file dates from 1989, and from me with two versions from 1995. As far as I am aware, not all these versions were collected by when the Sourceforge repo was started, so they could not have been made part of the history. But now they are there and you have the chance to correct this!

Regards,
-Olaf

**Comment by thomas374b** [comment]
I have a source tarball of dasm where the latest file is dated 24th June 1993. I don't recall where I downloaded it. No any SVN stuff inside. Is that 'historic' enough ?

**Comment by dionoid** [comment]
Closing this issue
