### ISSUE TITLE
byte not range-checked

### ISSUE THREAD

**Issue by andrew-davie** [dasm-assembler/dasm#22]
` .byte 256`

This results in 00 being placed in the output binary.
In other words, the low byte is used.

I believe this statement should be flagged as an error 'value out of range' or something like that.
For example, if you have 

` .byte $FFFF` 

You end up with just one $FF in the output, not two as you might (wrongly) expect.

**Comment by msaarna** [comment]
Fixed in master. I added out of range checking for .byte and .word value data.
