### ISSUE TITLE
Error substracting label values

### ISSUE THREAD

**Issue by FabienTregan** [dasm-assembler/dasm#24]
Hi,

  I have some self modifying code. Since I need to copy it to ram, I put some label in ROM, and then  add the difference between position of the code in the rom and the position where I copy it in ram.

  I hoped to calculate the position of the code where it will be in RAM like this :

```
Col7_1                  equ     InMemoryCode + _col7_1 - _InMemoryCode
```

  Where `_col_7_1` is a label in the code in ROM, `_InMemoryCode` the label at the beginning of the code when it's compiled in the ROM, and `InMemoryCode` a label at the place where the code is copied in RAM.

  Unfortunately, this doesn't work. If I try to `inc Col7_1`, I get this error on a subsequent line :

```
Rainbow.a (94): error: Label mismatch...
 --> BackToRom f096
Rainbow.a (99): error: Label mismatch...
 --> 8.waittimer f09d
```

If I replace the `-` with a `+` in the definition of `Col7_1`, it works (but with wrong value calculated of course).

The following definition works :
```
InMemoryCodeLength      equ     _InMemoryCodeEnd - _InMemoryCode
```

_InMemoryCode is $f000
InMemoryCode is $0083 (or $83 ? I do a `ds InMemoryCodeLength` in the variable segment)

I would be happy to share the code f it helps, but would prefer to share it privately.

**Comment by FabienTregan** [comment]
If I do not use the constant for the `inc`instruction, the code compile and the `.sym` file contains :
```
_InMemoryCode            f200              (R )
_InMemoryCodeEnd         f277              (R )
InMemoryCode             0083              (R )
InMemoryCodeLength       0077              (R )
...
_col7_1                  f213              (R )
```
0083 + f213 - f200 is 0096. If I hardcode $0096 instead of using the constant, the code works.

**Comment by andrew-davie** [comment]
Hard to tell without some sample code to play around with.
But just out of curiosity, how does it behave if you change the EQU to SET ?

**Comment by FabienTregan** [comment]
Same thing with set.

i remove most of the code that get copied and still have the problem. in the attached file, replacing the minus with a plus in the second "equ" make it possible to assemble the file.

[bug.zip](https://github.com/dasm-assembler/dasm/files/4032620/bug.zip)

**Comment by FabienTregan** [comment]
I use the release from three weeks ago :
```
$ ../dasm.exe
DASM 2.20.12
Copyright (c) 1988-2019 by the DASM team.
```

**Comment by andrew-davie** [comment]
The provided code assembles fine for me.
That is, with the line…

Col7_1			set	InMemoryCode + _col7_1 - _InMemoryCode

I am using dasm DASM 2.20.13-SNAPSHOT but I doubt that’s the difference.

**Comment by FabienTregan** [comment]
I am using dasm-2.20.12-win-x64.zip, I will try on linux tomorrow.

**Comment by FabienTregan** [comment]
Building from the mater branch under linux gives me a version that can compile the fil that doesn't work with latest realease on for windows : 
```
$ bin/dasm Rainbow.a -f3 -oo.bin -so.sym -lo.lst

Complete.

$ bin/dasm
DASM 2.20.13-SNAPSHOT
...
```

I'll try to build the snapshot for windows tomorrow.

**Comment by msaarna** [comment]
Confirmed that Andrew's "bug.zip" fails in 2.20.12 (and earlier) and builds in the current master. I believe this was fixed in the "[address expression fix](https://github.com/dasm-assembler/dasm/commit/b95b1a02aee867903a0c8ce47cf6207c375558ab#diff-25d902c24283ab8cfbac54dfa101ad31)" update.

You can always grab a snapshot of the current master [from here](https://github.com/dasm-assembler/dasm/tree/master/snapshot-builds).

Fabien when you can, please confirm, and I'll close the issue.

**Comment by FabienTregan** [comment]
Yes, it works on both linux and windows with the latest snapshot,thanks !
