### ISSUE TITLE
Defining a constant with value ofa label fails on latest nightly build

### ISSUE THREAD

**Issue by FabienTregan** [dasm-assembler/dasm#25]
The following code fails with to compile on windows, with both x86 and x64,with build from commit a3e6790722c4f4337dbac1c472cf2134db7c3061

```

	processor       6502


InMemoryCodeLength	equ	InMemoryCodeEnd

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Variables segment

        seg.u	Variables
        org	$80


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Code segment

	seg	Code
        org	$1000

; ----  modified code-> copied to memory  ----------------

Start
        
        nop

InMemoryCodeEnd

        nop

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Epilogue

	org $fffc
        .word Start	; reset vector
        .word Start	; BRK vector


             MAC SOME_MACRO
                nop
             ENDM
```
```
dasm.exe rainbow.a -obuild/o.bin -lbuild/o.lst -sbuild/o.sym -f3
rainbow.a (38): error: Macro "some_macro" defintion is repeated.

Unrecoverable error(s) in pass, aborting assembly!
Complete.
```
In addition to the typo (defintion -> definition), what is orth noting is :

- If you remove `InMemoryCodeLength	equ	InMemoryCodeEnd`, the code compiles (though the error message is about duplicated macro which is abviously not duplicated)
- If you remove the maco definition, it also compiles fine
- If you use build from previous snapshot build ( a3e6790722c4f4337dbac1c472cf2134db7c3061 ) it also does compile fine.

**Comment by msaarna** [comment]
Thanks for the report! Looks like an unintended consequence of the "error on duplicate macro" update. I've reverted that update, and the snapshots were updated.
