### ISSUE TITLE
crash on assembly

### ISSUE THREAD

**Issue by andrew-davie** [dasm-assembler/dasm#29]
I'm getting a crash in 2.20.13 (compiled locally) on assembling a large program.
Running on MacOS.
Symptoms are I add code/data (as include files), it crashes. Remove it, it's happy.
Doesn't really matter what the code is, it seems. In this case it's data statements.

Here's the error...

../dasm/bin/dasm ./chess.asm -l./chess.lst -f3 -s./chess.sym -o./chess.bin || (echo "mycommand failed $?"; exit 1)
/bin/sh: line 1: 85600 Illegal instruction: 4  ../dasm/bin/dasm ./chess.asm -l./chess.lst -f3 -s./chess.sym -o./chess.bin
mycommand failed 132

I have tried with the precompiled MacOS 64-bit version, and that exhibits slightly different behaviour -- it simply never returns. But no error.

Not sure quite how to track this down - I would prefer not to upload many megabytes of code for testing.

**Comment by andrew-davie** [comment]
A clue... possibly probably caused by
BANK_FIXED.asm (19): error: Origin Reverse-indexed.
I suspect there's code in dasm that is not gracefully coping with this situation.

**Comment by msaarna** [comment]
My first guess is that there's an issue with memory access beyond what's been allocated, in some certain circumstances. If that's right, I might have a hunch where that's happening.

Can you get a hold of valgrind for MacOS, and try running dasm to build your project with the following prepended to the command?  "valgrind --tool=memcheck --leak-check=yes "

We may need to get you a copy of dasm built with -O0 and -g switches, to provide any offending dasm source code lines, but even without that valgrind will at least report if out-of-bounds access has happened.

**Comment by msaarna** [comment]
Give [this version](http://7800.8bitdev.org/images/4/43/Dasm.buffermod.zip) a shot, and see if it behaves any better.

**Comment by andrew-davie** [comment]
Unfortunately I cannot run valgrind on MacOS because it currently does not compile on the OS.
Specifically... they report that it  "does not compile or function as expected on macOS versions newer than High Sierra due to an upstream incompatibility."  I have tried building from source, and also installing via brew. No luck at all.

**Comment by andrew-davie** [comment]
First test with the new version - YES, it appears to be working.

**Comment by msaarna** [comment]
Ok, that would seem to confirm that my hunch was right. We have static buffers for the code that suppresses pass output, though they're massively sized. I guess your project was more massive than the buffers.
The version I gave you uses dynamic buffers, that grow as required. The updated code will be hitting master shortly.

**Comment by msaarna** [comment]
Given we have the fix in master, and no complaints so far, I'll close this one out.

**Comment by andrew-davie** [comment]
Not sure if this is fixed, unfortunately. I am getting a similar error - latest dasm code pulled to check
I've attached my source code to help with diagnosis - all I'm getting is...

`boo@Andrews-MacBook-Pro chess % ../dasm/bin/dasm ./chess.asm -f3 -o./chess.bin

Unrecoverable error(s) in pass, aborting assembly!
Complete.
`

The code will not generate a playable binary, but it should at least assemble, or report what the error actually is.

[chess.zip](https://github.com/dasm-assembler/dasm/files/4221787/chess.zip)

**Comment by andrew-davie** [comment]
... is this actually generating a correct binary, but just incorrectly reporting an error...???

**Comment by thrust26** [comment]
Anything in the list file?

**Comment by andrew-davie** [comment]
The list file looks complete. I don't know what to search for, really... it's huge.
Also, correct size binary generated, and it does appear to startup but the code was in a non-working state so I can't actually check easily that all is OK.

**Comment by thrust26** [comment]
Search for "error".

**Comment by andrew-davie** [comment]
OK, got it.
Unknown mnemonic - a macro was used in a file in which it was not defined.
Would be nice to have a better diagnostic/report from dasm on this, as it just skipped the line, assembled the rest of it, produced a full list file and binary, and reported "error" at the end.

```
BANK_GENERIC.asm (63): error: Unknown Mnemonic 'PHASE'.
```

**Comment by msaarna** [comment]
Yeah, that should be fatal. I'll look into it.

**Comment by msaarna** [comment]
Weird. It seems to work for me...

```
$ cat unknownmacro.asm
;   Unknown mnemonic/macro

	processor 6502
	ORG $1000

	lda #1
	TEST
	lda #1
$ dasm unknownmacro.asm -f1 -ounknownmacro.bin -lunknownmacro.list.txt -DINEEPROM
unknownmacro.asm (7): error: Unknown Mnemonic 'TEST'.

Unrecoverable error(s) in pass, aborting assembly!
Complete.
```

**Comment by andrew-davie** [comment]
The macro IS defined in another file. Perhaps that might be a difference?

**Comment by andrew-davie** [comment]
To clarify, the code started compiling when I simply MOVED the macro to the top-level file.
It would not compile when PHASE macro was in BANK_stateMachine.asm but compiles fine when I moved it to chess.asm
No changes to the macro, or the code that used it.

**Comment by msaarna** [comment]
Ah, I see. That one sounds like it's going to take a bit of code review to figure out. I'll have a look when I get a chance.

**Comment by andrew-davie** [comment]
One "clue" -- it seems that macros **must** be defined before use. 
You can't have a macro 'resolve' in subsequent passes, which is a bit of a shame.
Pretty sure this is the crux of the error I was getting.
For example, the following will not compile...

```
;   Unknown mnemonic/macro

	processor 6502
	ORG $1000

	lda #1
	TEST
	lda #1

    MAC TEST
    lda #2
    ENDM

; EOF
```

**Comment by msaarna** [comment]
Nice detective work. As an enhancement, I can look at making the "unknown mnemonic" error one that doesn't immediately abort, but instead pushes for another pass.

I'll wait for the upcoming release to get put out, before I start messing with it.

**Comment by andrew-davie** [comment]
OK, I know how to trigger/disable the error at will. Basically if you have a forward-reference to a macro, then yes you get an error with details. But if you trigger a 2nd pass of the assembler by having a forward label reference TOO, then you don't get the error details.  Sample code shows this in action. Enable/comment out the "jmp" and you get the two variants.

```
;   Unknown mnemonic/macro

    processor 6502
    ORG $1000

    jmp .forward

    lda #1
    TEST
    lda #1

    MAC TEST
    lda #2
    ENDM

.forward
; EOF
```

Output with the "jmp" enabled...

```
boo@Andrews-MacBook-Pro chess % ../dasm/bin/dasm ./test.asm -f3 -o./test.bin

Unrecoverable error(s) in pass, aborting assembly!
Complete.
```
Output with the "jmp" disabled...

```
boo@Andrews-MacBook-Pro chess % ../dasm/bin/dasm ./test.asm -f3 -o./test.bin
./test.asm (10): error: Unknown Mnemonic 'TEST'.

Unrecoverable error(s) in pass, aborting assembly!
Complete.
```

**Comment by andrew-davie** [comment]
Created new issue #30 for the forward-reference macro
