### ISSUE TITLE
Are you interested in a Web interface to DASM?

### ISSUE THREAD

**Issue by JeremyJStarcher** [dasm-assembler/dasm#31]
I've recently gotten DASM to compile into a Web Assembly (WASM) module.

The process required no changes to the DASM source code.  (Congrats on that, BTW), a tiny amount of glue-code and some minor changes to the Makefiles.

I'm planning on tying this into a 6502 emulator as well.

Are you interested in having any of these changes back upstream?

This could be the base for anything from a CodePen style demo page to an Atari 2600 IDE.

**Comment by msaarna** [comment]
I appreciate the offer, but I don't think we can take on code for a target that none of the current maintainers are using, or plan to use. Testing and fixes would be an issue, especially since it doesn't fit into our automated testing tools.
Kudos on the super cool project, though. :)
