### ISSUE TITLE
Force extended addressing mode?

### ISSUE THREAD

**Issue by tobiasvl** [dasm-assembler/dasm#41]
Perhaps a bad idea, but I'm using `dasm` to write a program for the MC6800. 6803 code is backwards compatible with 6800's documented instructions, so I thought it'd be a safe thing to do.

However, I just encountered a problem:

    JSR $0040

On a 6800, this would use extended addressing, since there's no direct (zero-page) JSR there, so it would be assembled into `$BD $0040`. The 6803 does have a direct JSR instruction though, and `dasm` will obviously use it, creating code that's not compatible with 6800.

In this specific case, it's even worse. The opcode for direct JSR on 6803 is `$9D`, which on the 6800 was an undocumented opcode: The mythical "[halt and catch fire](https://en.wikipedia.org/wiki/Halt_and_Catch_Fire_(computing)#Motorola_6800)"!

Anyway, my actual question is this: I realize `dasm` doesn't support 6800 and that maybe I should use something else, but is there a way to force it to use extended addressing in cases like this, without simply inputting the raw bytes?

**Comment by andrew-davie** [comment]
How about creating a macro for that situation and using the macro in an opcode-like fashion?
Something like...

```
    MAC JSRX ;{addr}
            .byte $BD
            .word {1}
    ENDM
```

Then you'd just never use "JSR" but instead always "JSRX"

Not quite answering your question about "forcing" but perhaps a better solution than inputting the raw bytes every single time.

**Comment by tobiasvl** [comment]
Yeah, that's not the worst idea for my particular use case. Thanks.

And I do realize I probably shouldn't dasm for 6800. but I've used dasm for F8 in the past and I quite like it. Maybe the solution is to add 6800 support to dasm…

**Comment by tobiasvl** [comment]
The `vasm` assembler has the following feature:

> When an instruction supports direct and extended addressing mode the < character
can be used to force direct mode and the > character forces extended mode. Otherwise
the assembler selects the best mode automatically, which defaults to extended mode
for external symbols.

Could be something to consider.

**Comment by thomas374b** [comment]
Have you tried the postfix '.w'   

      jsr.w       $40

Should create  'bd 00 40'  (I've tested this)

With dasm one can force addressing mode to direct address with postfix (.b) or to extended address (.w)

**Comment by tobiasvl** [comment]
Oh, interesting! No, I must have missed that in the documentation. Not sure if this kind of syntax is common and I just don't know about it. This looks perfect.

**Comment by thomas374b** [comment]
My admin-gurus at the university used to say: "You've got the sources, luke .." (especcially when docs where missing ;-)
src/main.c around line 1030 you should find it.
With dasm this extension works for any opcode where both addressing modes are available.

**Comment by thrust26** [comment]
Can this be closed?

**Comment by tobiasvl** [comment]
Yes. Thanks!
