### ISSUE TITLE
dv.w only accepts <256 values

### ISSUE THREAD

**Issue by FabienTregan** [dasm-assembler/dasm#43]
Trying to use `dv.w` works for my only if passed value is < 256 :
```
plop EQM .. + 1

	dv.b  plop $ab, $12
	dv.w  plop $ab, $12
	dv.w  plop $abcd, $1234
``` 
gives:
```
    189  f249                              plop       EQM       .. + 1
[...]
    196  f24d                  ac 13                  dv.v      plop $ab, $12
    197  f24f                  ac 13                  dv.v      plop $ab, $12
copperbar.a (198): error: Value in 'dv 43982' must be <$100.
copperbar.a (198): error: Value in 'dv 4661' must be <$100.
    198  f251                  ce 35                  dv.v      plop $abcd, $1234
```
Using: DASM 2.20.13 release

**Comment by FabienTregan** [comment]
(also note that though the scond code doesn't give an eror message, I used `dv.w` but the output is `$ac $13` instead of `$00ac $0013`)

**Comment by msaarna** [comment]
It appears DV is erroneously going through a section of code specific to DC,DB,and DW, that sets up the data size according to the second character in the opcode. This is why your list shows "dv.v" in place of the hints you actually used. "v" isn't a real hint, so the default type of byte applies.

We only recently added data size checks. I believe your bug has been with dasm for a very long time, but just silently truncating the dv data from words to bytes.

**Comment by msaarna** [comment]
I've committed a fix to master, which works on your test case. Check out one of the [snapshot builds](https://github.com/dasm-assembler/dasm/tree/master/snapshot-builds) and let me know how it goes.

**Comment by FabienTregan** [comment]
Yes, you fixed it, thank you :D

**Comment by msaarna** [comment]
Excellent! You're welcome. :)
