### ISSUE TITLE
MACRO/redefinition

### ISSUE THREAD

**Issue by andrew-davie** [dasm-assembler/dasm#48]
I would like to see dasm treat redefinition of a macro as an ERR
Failing that, there should be a warning.
It's a silent failure mode otherwise, where code you think is executing actually isn't... because the macro you are modifying is being shadowed by another of the same name.

**Comment by msaarna** [comment]
Use strict checking (-S) in your dasm arguments. Macro duplication is flagged in that mode.

**Comment by andrew-davie** [comment]
Perfect, TY.  And I see it's in the manual - albeit obscure - me bad.
