### ISSUE TITLE
.sym file corrupted for -T1

### ISSUE THREAD

**Issue by thrust26** [dasm-assembler/dasm#51]
If you assemble with `-T1`, the resulting .sym file has a lot of labels duplicate but with different values. Since the file size is about identical, I suppose something goes wrong when sorting.

**Comment by thomas374b** [comment]
can you please add a *.asm file to the test folder to reproduce this error ?
With my projects everything seems to be OK. I don't get duplicate symbols

**Comment by thrust26** [comment]
I can't reproduce the bug with latest DASM anymore.
