### ISSUE TITLE
Segfault with hexadecimal notation

### ISSUE THREAD

**Issue by thomas374b** [dasm-assembler/dasm#53]
Typically old assemblers use dollar '$' sign as prefix for hexadecimal numbers. This causes problems when using on command line in shell scripts or in Makefiles since the dollar sign is the prefix for an environment variable in those contexts. Therefore it would be a nice feature is dasm would understand '0x' as a valid prefix for hexadecimal numbers.

As long as this is not supported dasm throws an segmentation fault when given in a define on the command line i.e.

  dasm  anysource.asm -DRAMSTART=0x60

The result is a segmentation fault and the user will not know the reason for the error.

**Comment by dionoid** [comment]
fixed in 2.20.14 release

**Comment by dionoid** [comment]
fixed in 2.20.14 release
