### ISSUE TITLE
dasm locked up in an endless loop

### ISSUE THREAD

**Issue by thomas374b** [dasm-assembler/dasm#56]
Sometimes when you've made a special kind of coding mistake in your asm-code, dasm does never return from assembling. It seems to be locked up, running in an endless loop. It has to be terminated by pressing Ctrl-C. The user gets no clue where the error is located.  Unfortunately I can't reproduce the error anymore, but I've had this problem in the past. I addressed it and I have a solution/bugfix already done.  

If you experience the same behaviour, please write a testcase (put that asm file to the test folder).

**Comment by andrew-davie** [comment]
If you generate a listing file during assembly, this is often a useful place to determine what the assembler was doing - if you're lucky it will help identify such issues.

**Comment by dionoid** [comment]
fixed in 2.20.14 release
