### ISSUE TITLE
misleading comments to adress modi in asm.h

### ISSUE THREAD

**Issue by thomas374b** [dasm-assembler/dasm#57]
the comments to enumeration ADDRESS_MODES in file asm.h seem to be misleading to me. Only the symbols
AM_IMP, AM_IMM8, AM_IMM16, AM_BYTEADR, AM_0X and AM_0Y have (for me) reasonable correct comments. The others seem to be shifted or swapped.

I came across this when I tried to extend the address modi.

**Comment by dionoid** [comment]
Fixed in 2.20.14

**Comment by dionoid** [comment]
Fixed in 2.20.14
