### ISSUE TITLE
test folder needs cleanup

### ISSUE THREAD

**Issue by thomas374b** [dasm-assembler/dasm#60]
In the test folder there are files for 'false-positive' testcases that are also added to the list of normal testcases.

A testcase should either fail or succeed not both.

**Comment by thomas374b** [comment]
> In the test folder there are files for 'false-positive' testcases that are also added to the list of normal testcases.
> 
> A testcase should either fail or succeed not both.

I commited the necessary changes to the master branch of my dasm fork a999a9d

**Comment by msaarna** [comment]
Those test cases are for strict-mode assembly. There are certain cases which should assemble without strict mode enabled, but be rejected with strict mode on. Failing with strict mode on is a pass of the test, because it shouldn't assemble.

**Comment by thomas374b** [comment]
Why should an obviously wrong statement be no error without the strict mode flag ?

Imagine the value would be calculated from other symbols. You include some additional code, the value grows and will not fit into the desired space/register. The result would be wrong code.
