### ISSUE TITLE
forced byte address mode ignored

### ISSUE THREAD

**Issue by thomas374b** [dasm-assembler/dasm#62]
If explicit byte address mode is wanted by using mnemonic extension and the value is too large there will be no error shown.
example
ram_start   .equ   $80
ram_addr  .equ    (ram_start + 192)
     lda.b    RAM_ADDR

dasm should abort assembly with proper error message when the user explicitly wanted byte addressing mode but
the value evaluates to something bigger than 255

**Comment by dionoid** [comment]
Fixed in 2.20.14
