### ISSUE TITLE
assembly succeeded in subsequent pass but dasm aborts with errorcode

### ISSUE THREAD

**Issue by thomas374b** [dasm-assembler/dasm#64]
If there is a constant to be defined and its value is derived from a calculation which involves a not-yet known symbol, its value can become negative or too large. dasm returns with failure even if the symbol gets resolved in subsequent passes.

dasm should return with errorlevel only if the problem persists to the last pass.

**Comment by dionoid** [comment]
Fixed in release 2.20.14
