### ISSUE TITLE
dasm creates wide-char strings in opposite byte-order as desired

### ISSUE THREAD

**Issue by thomas374b** [dasm-assembler/dasm#65]
I tried to create a wide-char string in little-endian byte-order. This failed since my 'processor' has MSB order. It would be a nice feature if dasm have another extension to DC that creates word in the opposite byte-order. i.e.

DC.w "unicode"   ; bytes order same as with current 'processor'
DC.s "unicode"    ; opposite byte order  ; 's'  ~ abbrev. for 'short swap'

**Comment by dionoid** [comment]
https://github.com/dasm-assembler/dasm/issues/65
