### ISSUE TITLE
another lockup/supercat bug

### ISSUE THREAD

**Issue by thomas374b** [dasm-assembler/dasm#69]
If 'set' is being used recursively, dasm locks up in a loop until a very huge file is created. The final size of the file is constraint only by the operating systems capabilities (in my case 2GB). The effect of the bug is similar to the 'supercat' testcase but it can't  be detected by the recursion countermeasures.

Dasm should stop recursively generating bytes at a given threshold.

**Comment by dionoid** [comment]
fixed in 2.20.14 release

**Comment by dionoid** [comment]
fixed in 2.20.14 release
