### ISSUE TITLE
missing return with error code?

### ISSUE THREAD

**Issue by iddq** [dasm-assembler/dasm#7]
https://github.com/dasm-assembler/dasm/blob/b6b90fa2f09d4b253e0603787de2779cf88777f9/src/main.c#L702

**Comment by andrew-davie** [comment]
I do not think this is an error.
The code continues, and gets to the error code return about 20 lines down.

**Comment by iddq** [comment]
the return code is 0 in case of Unrecoverable error.

**Comment by andrew-davie** [comment]
> the return code is 0 in case of Unrecoverable error.

Ah, so it is. OK, this needs to be fixed - you are correct, TY.

**Comment by msaarna** [comment]
I've added a general non-abort error code, and this is now being returned for the code in question. (updated in master)
