### ISSUE TITLE
Double carriage returns in listing

### ISSUE THREAD

**Issue by thrust26** [dasm-assembler/dasm#71]
Currently DASM is creating double carriage returns (0x0d, 0x0d, 0x0a) for code segments in the listing file (Windows). This creates extra empty lines and thus makes the listings hard to read during debugging.

**Comment by msaarna** [comment]
Can you check out [this build](https://github.com/dasm-assembler/dasm/actions/runs/203051031), and see if it works? I'm having some trouble testing, but I think it should do the trick.

**Comment by thrust26** [comment]
Yup, that does it. :+1:

**Comment by msaarna** [comment]
Excellent!
