### ISSUE TITLE
Will somebody please write a full and complete manual for DASM?

### ISSUE THREAD

**Issue by Vascillious** [dasm-assembler/dasm#73]
It's fast and efficient, but I've heard the manual isn't up to date, and even if it is what's there reads more like student notes than a proper manual. It has the potential to be a very useful assembler. Please will somebody write a complete manual with all of its current features?

**Comment by msaarna** [comment]
Wonderful work, Andrew. Latex is perfect... when you're happy, we can put that source in github too! :+1:

**Comment by andrew-davie** [comment]
Update. Now with a "Change Log" just after the title page.
[dasm20200824.pdf](https://github.com/dasm-assembler/dasm/files/5115853/dasm20200824.pdf)

**Comment by andrew-davie** [comment]
> Wonderful work, Andrew. Latex is perfect... when you're happy with it, we can put that source in github too! 👍

I'm happy with it as a basic starting point. Attached ZIP contains all the latex files required for a build, and latest manual.
Could you please check all is included, it works OK, and then can we please add this to git so that I can start using it properly?
Note, one of the packages (phdthesis.sty) is GPL'd 3.0, I think that should be OK.

**Comment by andrew-davie** [comment]
> Wonderful work, Andrew. Latex is perfect... when you're happy with it, we can put that source in github too! 👍

Ready to go. There's a couple of GPL3 .sty files in there - no issue, I think.
I checked that I could load "dasm.tex" and successfully built a PDF using texstudio from that.
[dasm.zip](https://github.com/dasm-assembler/dasm/files/5117661/dasm.zip)

**Comment by dionoid** [comment]
The manual is a joy to read, Andrew! It reminds me of the first time that I
read your "Atari 2600 Programming for Newbies" posts.
I've placed dasm.pdf in the /manual folder of the dasm git repo, and copied
the LaTeX sources to the /manual/sources subfolder.
Do you think this documentation / user guide would eventually replace the
/doc/dasm.txt file?

Thanks,
Dion

**Comment by andrew-davie** [comment]
> Do you think this documentation / user guide would eventually replace the /doc/dasm.txt file?

That was my hope.
The only thing not included was the prefaces from Matt, Peter and myself.

**Comment by andrew-davie** [comment]
> I've placed dasm.pdf in the /manual folder of the dasm git repo, and copied the LaTeX sources to the /manual/sources subfolder.

I'm wondering why this location, instead of the 'docs' folder?
The welcome text specifically states that docs/manuals are in the 'docs' folder -- and it seems odd to me to have two folders for eseentially the same thing.

**Comment by dionoid** [comment]
> The welcome text specifically states that docs/manuals are in the 'docs' folder -- and it seems odd to me to have two folders for eseentially the same thing.

Yes, agree. I moved the manual into the /docs folder, and also changed the dasm main website to link to the new PDF documentation.
Btw: I like how you went from using uppercase DASM to lowercase dasm, even matching the color of the logo :-)

**Comment by thrust26** [comment]
> Btw: I like how you went from using uppercase DASM to lowercase dasm...

Grrr! 😈

**Comment by Vascillious** [comment]
Awesome! I am very impressed with how responsive that was. Well done! I am trying to popularise DASM in 64 groups. Thanks you. :)

**Comment by andrew-davie** [comment]
> Awesome! I am very impressed with how responsive that was. The result is excellent. Well done! I am trying to popularise DASM in 64 groups. Thank you. :)

Only weeks and weeks of work; no problem!  ;)
