### ISSUE TITLE
stuff removed...?

### ISSUE THREAD

**Issue by andrew-davie** [dasm-assembler/dasm#76]
Doing the documentation in the past week or so, I've stumbled across a few things that are in my local slightly older version of dasm, but which are not in the latest master version. But I don't seem to have spotted these changes or any discussion of them on the issues board, and I thought I'd leave a note here so I can understand/find out what I'm missing.

1. command line options -R and -m# have disappeared. Although these may debatably be useless, it would be nice to have their removal specifically noted. I have probably missed it, but thought it worth noting.

2. The 0x prefix for hexadecimal number entry was removed. This was not something I really used, but it used to work, and has been removed, apparently. I'm just wondering why.

**Comment by msaarna** [comment]
I'm looking at the initial upload of 2.20.10 we populated github with, and [I'm not seeing](https://github.com/dasm-assembler/dasm/blob/d62a9821cce64253d7468b4c3646b5bcf2430f6d/src/main.c) those options implemented. I'm not familiar with the options, so I don't know when they were originally added - was it during our watch, or in a historic version?

**Comment by andrew-davie** [comment]
It seem the version I was looking at is a snapshot of thomas's code/changes...?  I spotted an issue regarding 0x being added for hex numbers. As to the -R and -m# options, I have no idea about those ones yet. But in answer to your question ... recent, and now the hex one is understood, possibly all related to thomas's stuff.

**Comment by msaarna** [comment]
Ok, I'll let @dionoid comment on that, as it sounds like there might be some changes from that tree not yet merged to the master. I haven't really kept up with the status there.

**Comment by dionoid** [comment]
Hi, the starting-point of this git repository were the sources for dasm 2.20.10 and 2.20.11, which were downloaded from the SourceForge repo. The stuff that Andrew is missing, wasn't in these sources, so either it was removed before 2.20.10 (2008-03-28), or it was added to the SourceForge repository after 2.20.11 (2014-03-04).

It looks like thomas added the '0x'-prefix notation back in, right?

**Comment by andrew-davie** [comment]
> Hi, the starting-point of this git repository is the SourceForge sources for dasm 2.20.10 and 2.20.11. The stuff that Andrew is missing doesn't seem to be in these sources, so either it was removed before 2.20.10 (2008-03-28), or it was added to the SourceForge repository **after** 2.20.11 (2014-03-04) and only live in SourceForge.
> 
> I looked in main.c to get the list of supported command line options. @andrew-davie: is this where the missing options should be?
> And about the problem you found with the recently added '0x'-prefix notation: can you add a issue for that?

Yes, basically it boils down to me just picking random versions of dasm on my system from god-knows-where, and using those for writing the documentation. It didn't occur to me that I'd be catching brand new stuff that wasn't officially released yet. Me bad.
