### ISSUE TITLE
multiline comments

### ISSUE THREAD

**Issue by msaarna** [dasm-assembler/dasm#77]
This is an enhancement request for C style /* */ comments. I have the code, which I'll be pushing to master shortly.

Some suggested documentation comments follow...

Comments

Dasm has two different comment styles available, traditional assembler single-line ";" comments, and C-style "/* */" multiline comments.

Multiline comments make it easy to turn large blocks of code or text into comments.  The "/*" characters indicate the start of a comment block, and the "*/" characters indicate the end of a block.

Valid multiline comment examples...

/* This single line comment is valid */

   lda #1 /* And this comment is valid too */

/* And so is this
   Multiline comment */

Inserting comments before a label or opcode isn't supported in dasm.

Invalid multiline comment examples...

/* the opcode to the right will be ignored */ lda #1

/* and so is the opcode
   that follows this block
*/ lda #1

**Comment by msaarna** [comment]
[C-style multiline comments was added to the master](https://github.com/dasm-assembler/dasm/commit/d8d6c5dfd0275a9c0f8b13733117a1ace0fcf021)

**Comment by thrust26** [comment]
What happens with multiline comments inside multiline comments?

E.g. `/* abc /* 123 */ def */`

Does it assemble or not?

**Comment by andrew-davie** [comment]
Can you please test this with directives inside the comment block?
Something like 

```
 /* IF 0
*/
  echo "hello world"

**Comment by msaarna** [comment]
@thrust26, they're not recursive. (neither are the same multiline style in C, java, ...) In your particular example, the entire line would be a comment. (see the the "doc" text above inserting comments prior to label or opcode.) If it stretched across multiple lines, the first */ encountered would be the terminator, the second an unknown opcode or label, depending on it's position.

@andrew-davie, the functionality is part of the pre-interpreting cleanup, so it should work the same for everything. It just turns the block into a series of traditional single-line comments. Here's the list from your request...

------ FILE scratch.asm LEVEL 1 PASS 1
      1  0000 ????                                              ;/* IF 0
      2  0000 ????                                              ;*/
 hello world
      3  0000 ????                                    echo      "hello world"
      4  0000 ????

**Comment by andrew-davie** [comment]
Perfect, thanks.
The revised documentation will be up in about 5 minutes.

**Comment by andrew-davie** [comment]
Documentation updated ef0f21d35de20b0df8b85f65532ef5ed9c326caa

**Comment by andrew-davie** [comment]
A missing close-comment is not flagged by dasm.
That is, if you start a comment, then all the remaining code is not assembled.
It would be nice to flag this as an error.

**Comment by andrew-davie** [comment]
An isolated */ at the beginning of a line is interpreted as a label (!)
If there is whitespace before it, then it is reported as an error, as expected.

**Comment by msaarna** [comment]
I've updated master. Both cases will be flagged with a specific error now.

**Comment by andrew-davie** [comment]
TY. Tested and confirmed working on my use-cases.

**Comment by andrew-davie** [comment]
In the case where anything on a line after */ is ignored, this is a pretty non-obvious silent failure.
Could anything after */ on a line be flagged as an error, or at the very least a warning?
For example, I don't believe the following code should compile...

```
/*
 */ this is an error
```

**Comment by msaarna** [comment]
Here's the test case, in case anybody is curious...

` processor 6502
 ORG $1000

 /* comment 1 */ lda #0

 /* IF 0
*/

  lda #1/*test*/
 /*

*/  lda #2

/*
hello */label lda #3

/*foo*/ lda #4/*bar*/

/* more 
   comments
     */mylabel lda #5 /* too many comments*/ /*but we can deal with it*/
`

**Comment by msaarna** [comment]
Docs have be kindly updated by Andrew. Closing off this issue.
