### ISSUE TITLE
MacOS / compatibility reminder

### ISSUE THREAD

**Issue by andrew-davie** [dasm-assembler/dasm#9]
I probably have an old version of dasm triggering this, but I thought I'd put the warning up as a note/reminder in case there is actually an issue with this that needs to be addressed. See image.

<img width="423" alt="Screen Shot 2019-09-13 at 9 44 13 pm" src="https://user-images.githubusercontent.com/16424075/64860245-edbfe180-d66f-11e9-8dee-2fa73f050ccb.png">

**Comment by dionoid** [comment]
This is because the released version of dasm is a 32-bit apps.
For release 2.20.12 I'll make sure also include the 64-bit versions for each supported OS (Windows, Linux and macOS). Then in a future release we can maybe switch to 64-bit only.

**Comment by dionoid** [comment]
make_dasm_all_platforms.sh was extended to make both 32 and 64-bit versions of dasm for all supported OS's
