### ISSUE TITLE
How to build documentation?

### ISSUE THREAD

**Issue by jnahmias** [dasm-assembler/dasm#95]
Hello,
I am currently trying to package dasm for the [Debian GNU/Linux](https://debian.org/) distribution. Part of the requirements is that everything must be built from the source during the packaging.
So, after installing the texlive-latex-extra and texlive-fonts-extra packages and running `pdflatex dasm.tex`, I get the message:
```
! LaTeX Error: File `important' not found.
```
Can you share the process you use to build the documentation?

**Comment by andrew-davie** [comment]
Try
```
pdflatex -synctex=1 -interaction=nonstopmode dasm.tex
```

**Comment by jnahmias** [comment]
Thanks for that. However, I still get the same error message. It looks like it's trying to find the exclamation point graphic at the beginning of Chapter 7 (Macros), but cannot find it.

https://github.com/dasm-assembler/dasm/blob/a87dd52964e180c7d8e600be8bcbef85873f71de/docs/sources/manual.tex#L2150

Any idea where it comes from?

**Comment by andrew-davie** [comment]
Right you are -- indeed, I have forgotten to add that file to the repository.
I have just done so, so hopefully if you do a fetch, it should now be working for you.
Sorry about that.

**Comment by andrew-davie** [comment]
Having just checked with a command-line build... I found that pdflatex seemed to have missing links (marked ?? in the PDF), but the following built a PDF (to my surprise) which was correct...

```
latex -src -interaction=nonstopmode dasm.tex
```

I guess 'latex' (at least in my environment) builds a PDF...

**Comment by andrew-davie** [comment]
Update.... ah, so you need to run the command TWICE to successfully resolve all the links.
That is, the first pass it will have '??' in the PDF.  The second time you run it, all is OK.

**Comment by jnahmias** [comment]
Thanks for adding the file -- that fixed it! FYI - I ended up using latexmk, `latexmk -pdf dasm.tex`, as it automatically figures out how many passes are needed to resolve all the references.
